# Generated by Django 4.2.6 on 2023-10-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
