# Generated by Django 4.2.6 on 2023-10-21 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_car_car_name_car_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('authore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='home.authore')),
            ],
        ),
    ]
