# Generated by Django 4.2.6 on 2023-10-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_authore_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='authore',
            name='print_year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='book',
            name='authore',
        ),
        migrations.AddField(
            model_name='book',
            name='authore',
            field=models.ManyToManyField(related_name='books', to='home.authore'),
        ),
    ]
