# Generated by Django 4.2.6 on 2023-10-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_authore_print_year_remove_book_authore_book_authore'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
                ('bio', models.CharField(max_length=255)),
                ('create_person', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
